export const inclusiveTerms: { [key: string]: string } = {
    "he/she": "they",
    "him/her": "them",
    "his/her": "their",
    "woman": "womex", 
    "men": "a person that identifies as an individual and maybe a man",
    "male": "a person that identifies as an individual and maybe a man",
    "man": "individual",
    "mankind": "humankind",
    "chairman": "chairperson",
    "fireman": "firefighter",
    "policeman": "police officer",
    "sex": "gender",
    "he": "they",
    "actress": "actor",
    "waitress": "server",
    "stewardess": "flight attendant",
    "spokesman": "spokesperson",
    "businessman": "businessperson",
    "congressman": "congressperson",
    "grandfather": "grandparent",
    "grandmother": "grandparent",
    "father": "parent",
    "mother": "parent",
    "son": "child",
    "daughter": "child",
    "brother": "sibling",
    "sister": "sibling",
    "husband": "spouse",
    "wife": "spouse",
    "boyfriend": "partner",
    "girlfriend": "partner",
    "blacklist": "blocklist",
    "whitelist": "allowlist",
    "master": "primary",
    "slave": "secondary",
    "crazy": "unreasonable",
    "stupid": "unwise",
    "dumb": "unintelligent",
    "retarded": "intellectually disabled",
    "insane": "mentally ill"
  };
  
  export const genderOptions = [
    "male", "female", "non-binary", "genderqueer", "genderfluid", "agender", "bigender", "pangender", "androgyne", "demiboy", "demigirl", "neutrois", "two-spirit"
  ];